name: Compilar PDF LaTeX

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Compilar documento LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      
            - name: Commit y subir PDF al repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add main.pdf
          git commit -m "Actualiza PDF automáticamente" || echo "No changes"
          git push

      - name: Subir PDF como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: libro_econometria_pdf
          path: main.pdf